fail workflow if container exit with non 124 error

diff --git a/.github/workflows/package_deploy.yml b/.github/workflows/package_deploy.yml
--- a/.github/workflows/package_deploy.yml
+++ b/.github/workflows/package_deploy.yml
@@ -39,7 +39,7 @@ jobs:
         run: docker push $REGISTRY/$DOCKER_IMAGE_NAME
 
 
-  test-image-locally:
+  test-newly-updated-image-locally:
     runs-on: ubuntu-latest
     needs: build-and-push-image
     steps:
@@ -64,6 +64,10 @@ jobs:
         run: docker pull $REGISTRY/$DOCKER_IMAGE_NAME
 
       - name: Run Docker container
-        run: docker run -v "$(pwd)/.env:/.env" $REGISTRY/$DOCKER_IMAGE_NAME
-        timeout-minutes: 1
-        continue-on-error: true
+        run: |
+          (timeout 30s docker run --env-file "$(pwd)/.env" $REGISTRY/$DOCKER_IMAGE_NAME) ||
+          if [ $? -eq 124 ]; then
+            echo "OK, timeout error is acceptable."
+          else
+            exit $?
+          fi
