fix

diff --git a/.github/workflows/push_heath.yml b/.github/workflows/push_heath.yml
--- a/.github/workflows/push_heath.yml
+++ b/.github/workflows/push_heath.yml
@@ -48,6 +48,5 @@ jobs:
           if [ $? -eq 124 ]; then
             echo "OK, timeout error is acceptable."
           else
-            echo "The job should not fail with this error. Error code: $?"
-            exit $?
+            echo "The job should not fail with this error. Error code: $?" & exit $?
           fi
